name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: List files
      run: find .
    - name: Run a multi-line script
      run: |
        cd ..
        find .
        https://github.com/mongodb/mongo-c-driver.git
        https://github.com/mongodb/mongo-cxx-driver.git
